- name: Install ntp
  apt:
    name: "ntp"
    state: latest

- name: Restart ntp
  shell: "service ntp restart"

- name: Checl ntp status
  shell: "service ntp status"

- name: Check original timezone
  shell: "timedatectl status"
  register: original_timezone

- debug: msg="{{ original_timezone.stdout }}"

- name: Set timezone
  shell: timedatectl set-timezone "Asia/Taipei"

- name: Check updated timezone
  shell: "timedatectl status"
  register: updated_timezone

- debug: msg="{{ updated_timezone.stdout }}"